import os
from typing import Any, Dict, Optional, Tuple

from dotenv import load_dotenv

from PA.utils.neo4j_utils import determine_environment_key
def select_neo4j_environment(
    override_value: Optional[str],
    config_value: Optional[str],
    logger: Optional[Any] = None,
) -> Tuple[Optional[str], Optional[str]]:
    """Determine which Neo4j environment to use based on override precedence."""

    for candidate in (override_value, config_value):
        if not candidate:
            continue
        env_lower, env_key = determine_environment_key(
            candidate, logger=logger, default_to_prod=False
        )
        if env_key:
            return env_lower, env_key

    return None, None

_MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_MODULE_DIR)
_DEFAULT_ENV_PATH = os.path.join(_PROJECT_ROOT, "PA", "keys", ".env")


def update_env_file(
    updates: Dict[str, Optional[str]],
    logger: Optional[Any] = None,
    env_path: Optional[str] = None,
) -> str:
    """Merge updates into the shared .env file and reload it."""

    path = env_path or _DEFAULT_ENV_PATH
    os.makedirs(os.path.dirname(path), exist_ok=True)

    env_data: Dict[str, str] = {}
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as existing_file:
            for line in existing_file:
                if "=" not in line or line.lstrip().startswith("#"):
                    continue
                key, value = line.strip().split("=", 1)
                if key:
                    env_data[key.strip()] = value.strip()

    for key, value in updates.items():
        if key and value is not None:
            env_data[key] = value.strip()

    with open(path, "w", encoding="utf-8") as updated_file:
        updated_file.write("# Auto-generated by AzureML pipeline\n")
        for key, value in env_data.items():
            updated_file.write(f"{key}={value}\n")

    load_dotenv(path, override=True)
    if logger:
        logger.info("Updated environment file at %s", path)
    return path


def apply_neo4j_credentials(
    config: Optional[Dict[str, Any]],
    uri: Optional[str],
    username: Optional[str],
    password: Optional[str],
    logger: Optional[Any] = None,
    env_path: Optional[str] = None,
    environment_override: Optional[str] = None,
) -> Tuple[str, str]:
    """Set Neo4j credentials in env vars and persist them to the shared .env file."""

    config = config or {}
    neo4j_config = config.get("neo4j", {}) or {}

    override_clean = (environment_override or "").strip() or None
    env_lower, env_key = select_neo4j_environment(
        override_clean, neo4j_config.get("environment"), logger=logger
    )

    if env_lower:
        neo4j_config["environment"] = env_lower
    else:
        neo4j_config.pop("environment", None)

    config["neo4j"] = neo4j_config

    env_specific_uri = (
        os.environ.get(f"NEO4J_URI_{env_key}") if env_key else None
    )
    env_specific_password = (
        os.environ.get(f"NEO4J_PASSWORD_{env_key}") if env_key else None
    )

    resolved_uri = (
        uri
        or env_specific_uri
        or neo4j_config.get("uri")
        or os.environ.get("NEO4J_URI")
    )
    resolved_username = (
        username
        or neo4j_config.get("username")
        or os.environ.get("NEO4J_USERNAME")
        or "neo4j"
    )
    resolved_password = (
        password
        or env_specific_password
        or neo4j_config.get("password")
        or os.environ.get("NEO4J_PASSWORD")
    )

    if not resolved_uri or not resolved_password:
        raise ValueError(
            f"Missing Neo4j credentials for environment '{env_lower}'. "
            "Ensure NEO4J_URI/NEO4J_PASSWORD (or their environment-specific variants) are defined."
        )

    clean_uri = resolved_uri.strip()
    clean_username = resolved_username.strip()
    clean_password = resolved_password.strip()

    updates: Dict[str, Optional[str]] = {
        "NEO4J_URI": clean_uri,
        "NEO4J_USERNAME": clean_username,
        "NEO4J_PASSWORD": clean_password,
        "NEO4J_ENVIRONMENT_RESOLVED": env_lower or "unspecified",
    }

    if env_key:
        updates[f"NEO4J_URI_{env_key}"] = clean_uri
        updates[f"NEO4J_PASSWORD_{env_key}"] = clean_password

    for key, value in updates.items():
        if value is not None:
            os.environ[key] = value

    if updates:
        update_env_file(updates, logger=logger, env_path=env_path)

    return env_lower, env_key
