import os
from typing import Any, Dict, Optional, Tuple

from dotenv import load_dotenv

from PA.utils.neo4j_utils import determine_environment_key

_MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_MODULE_DIR)
_DEFAULT_ENV_PATH = os.path.join(_PROJECT_ROOT, "PA", "keys", ".env")


def update_env_file(
    updates: Dict[str, Optional[str]],
    logger: Optional[Any] = None,
    env_path: Optional[str] = None,
) -> str:
    """Merge updates into the shared .env file and reload it."""

    path = env_path or _DEFAULT_ENV_PATH
    os.makedirs(os.path.dirname(path), exist_ok=True)

    env_data: Dict[str, str] = {}
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as existing_file:
            for line in existing_file:
                if "=" not in line or line.lstrip().startswith("#"):
                    continue
                key, value = line.strip().split("=", 1)
                if key:
                    env_data[key.strip()] = value.strip()

    for key, value in updates.items():
        if key and value is not None:
            env_data[key] = value.strip()

    with open(path, "w", encoding="utf-8") as updated_file:
        updated_file.write("# Auto-generated by AzureML pipeline\n")
        for key, value in env_data.items():
            updated_file.write(f"{key}={value}\n")

    load_dotenv(path, override=True)
    if logger:
        logger.info("Updated environment file at %s", path)
    return path


def apply_neo4j_credentials(
    config: Optional[Dict[str, Any]],
    uri: Optional[str],
    username: Optional[str],
    password: Optional[str],
    logger: Optional[Any] = None,
    env_path: Optional[str] = None,
) -> Tuple[str, str]:
    """Set Neo4j credentials in env vars and persist them to the shared .env file."""

    config = config or {}
    neo4j_config = config.get("neo4j", {}) or {}
    env_lower, env_key = determine_environment_key(
        neo4j_config.get("environment"), logger=logger
    )

    updates: Dict[str, Optional[str]] = {}

    if uri:
        clean_uri = uri.strip()
        os.environ["NEO4J_URI"] = clean_uri
        os.environ[f"NEO4J_URI_{env_key}"] = clean_uri
        updates["NEO4J_URI"] = clean_uri
        updates[f"NEO4J_URI_{env_key}"] = clean_uri

    if username:
        clean_username = username.strip()
        os.environ["NEO4J_USERNAME"] = clean_username
        updates["NEO4J_USERNAME"] = clean_username

    if password:
        clean_password = password.strip()
        os.environ["NEO4J_PASSWORD"] = clean_password
        os.environ[f"NEO4J_PASSWORD_{env_key}"] = clean_password
        updates["NEO4J_PASSWORD"] = clean_password
        updates[f"NEO4J_PASSWORD_{env_key}"] = clean_password

    if updates:
        update_env_file(updates, logger=logger, env_path=env_path)

    return env_lower, env_key
